FROM python

RUN pip install mlflow>=1.0 \
    && pip install numpy \
    && pip install scipy \
    && pip install pandas \
    && pip install scikit-learn \
    && pip install cloudpickle \
    && pip install keras==2.2.2 \
    && pip install matplotlib \
    && pip install Gpy \
    && pip install GpyOpt \
    && pip install pyDOE\
    && pip install tensorflow\
    && pip install hyperopt